language: java
notifications:
  flowdock: 
    secure: "CnIkzmFiuxhGYcVmdx8a+e3Bmf5BYMNeNu1BVsj92BG0+WVLg4E3NfPDbC2n7WYDrmiFZVwgEEe0MQyCRqBKcn4zzQftLG2tIiPm3ZaHzl8nWEKapTk4moti67Qg00shn7vbaIvJFueeSa4EPni1+nbjeB/9y4jPT3EBuGw74XU="
